foster_home/foster_home/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^$', 'users.views.landing_page_view', name='landing_page'),

    # TODO(kniski) find how to put login urlconf into users app
    url(r'^signin/$', 'users.views.signin_view', name='signin'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^signup/$', 'users.views.signup_view', name='signup'),
    url(r'^users/', include('users.urls', namespace='users')),  # TODO(kniski) design url for users list and user profile
    url(r'^animals/', include('animals.urls', namespace='animals')),

    # Examples:
    # url(r'^$', 'foster_home.views.home', name='home'),
    # url(r'^foster_home/', include('foster_home.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
]

# Uncomment the next line to serve media files in dev.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foster_home/users/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<username>[0-9A-Za-z_\-]+)/$', views.baseuser_detail_view, name='user_profile'),
    url(r'^(?P<username>[0-9A-Za-z_\-]+)/edit$', views.baseuser_edit_view, name='edit'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.user_activation_view, name='activation'),
]

foster_home/templates/includes/navbar.html
{% load form_tags %}
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url "landing_page" %}">FosterHome</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                {#                <li class="active"><a href="{% url "landing_page" %}">Home</a></li>#}
                {% if request.user.is_authenticated %}
                    <li><a href="{% url "users:user_profile" username=request.user.username %}">Profil</a></li>
                {% endif %}
                <li><a href="{% url "animals:list" %}">Zwierzęta</a></li>
                {#                <li><a href="#contact">Contact</a></li>#}
            </ul>
            {% if request.user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url "logout" %}">Wyloguj</a></li>
                </ul>
            {% else %}
                <form class="navbar-form navbar-right" method="POST" action="{% url 'signin' %}">
                    {% signin_form_fields %}
                    <button type="submit" class="btn btn-default">Zaloguj się</button>
                </form>
            {% endif %}
        </div><!--/.nav-collapse -->
    </div>
</div>