foster_home/foster_home/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^$', 'users.views.landing_page_view', name='landing_page'),

    # TODO(kniski) find how to put login urlconf into users app
    url(r'^signin/$', 'users.views.signin_view', name='signin'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^signup/$', 'users.views.signup_view', name='signup'),
    url(r'^users/', include('users.urls', namespace='users')),  # TODO(kniski) design url for users list and user profile
    url(r'^animals/', include('animals.urls', namespace='animals')),

    # Examples:
    # url(r'^$', 'foster_home.views.home', name='home'),
    # url(r'^foster_home/', include('foster_home.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
]

# Uncomment the next line to serve media files in dev.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foster_home/users/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<username>[0-9A-Za-z_\-]+)/$', views.baseuser_detail_view, name='user_profile'),
    url(r'^(?P<username>[0-9A-Za-z_\-]+)/edit$', views.baseuser_edit_view, name='edit'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.user_activation_view, name='activation'),
]

foster_home/users/models.py
import logging

from django.conf import settings
from django.core import signing
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.core.urlresolvers import reverse
from django.contrib.auth import models as auth_models
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext as _

log = logging.getLogger(__name__)


class UserManager(auth_models.BaseUserManager):

    def _create_user(self, username, email, password, is_active,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        now = timezone.now()
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        user = self.model(username=username, email=email,
                          is_staff=is_staff, is_active=is_active,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        return self._create_user(username, email, password, False, False, False,
                                 **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        return self._create_user(username, email, password, True, True, True,
                                 **extra_fields)


class BaseUser(auth_models.AbstractUser):
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message=_("""Phone number must be in entered
                                 in the format: '+999999999'. Up to 15 digits
                                 allowed."""))

    phone_no = models.CharField(max_length=15, blank=True, validators=[phone_regex])
    address = models.CharField(max_length=100, blank=True)
    call_before = models.TimeField(null=True, blank=True,
                                   help_text=_("""User can specify time beyond
                                    which he wouldn't pick up phone."""))

    objects = UserManager()

    def get_activation_key(self):
        key_template = '{username}.{email}.{date_joined}.{pk}'
        kwargs = {'username': self.username,
                  'email': self.email,
                  'date_joined': int(self.date_joined.timestamp()),
                  'pk': self.pk}
        return key_template.format(**kwargs)

    def get_activation_salt(self):
        return '{}.{}.activation_link'.format(self.pk, self.username)

    def generate_activation_uid(self):
        if self.is_active:
            return

        key = self.get_activation_key()
        salt = self.get_activation_salt()
        signer = signing.TimestampSigner(salt=salt)
        # (kniski) 'value' is redundant
        value, signature = signer.sign(key).split(':', 1)
        return signature

    def verify_activation_signature(self, signature,
                                    max_age=settings.ACTIVATION_LINK_MAX_AGE):

        if self.is_active:
            raise ValidationError(_('User is already active.'))

        signer = signing.TimestampSigner(salt=self.get_activation_salt())
        signature = '{}:{}'.format(self.get_activation_key(), signature)
        try:
            signer.unsign(signature, max_age=max_age)
        except signing.SignatureExpired:
            log.warning(_("User: %s signature expired."), self)
            return False
        except signing.BadSignature:
            log.warning(_("User: %s, bad signature."), self)
            return False
        return True

    def get_absolute_url(self):
        return reverse('users:user_profile', kwargs={'username': self.username})

foster_home/users/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth import forms as auth_forms
from django.utils.translation import ugettext as _

from .models import BaseUser


class SignUpForm(auth_forms.UserCreationForm):

    # FIXME(kniski) it should be enforced on model level
    email = forms.EmailField(label=_('Email'), required=True)
    terms_and_conds = forms.BooleanField()

    class Meta(auth_forms.UserCreationForm.Meta):
        model = BaseUser
        fields = ("username",)

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            self._meta.model._default_manager.get(username=username)
        except BaseUser.DoesNotExist:
            return username
        raise forms.ValidationError(
            self.error_messages['duplicate_username'],
            code='duplicate_username',
        )

    def register_user(self, commit=True):
        cleaned_data = self.cleaned_data
        del cleaned_data['terms_and_conds']
        cleaned_data['password'] = cleaned_data['password1']
        del cleaned_data['password1']
        del cleaned_data['password2']

        if commit:
            user = BaseUser.objects.create_user(**cleaned_data)
        else:
            user = BaseUser(**cleaned_data)
        return user

foster_home/users/views.py
import logging

from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
from django.views.generic import DetailView
from django.views.generic import FormView
from django.views.generic import UpdateView
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from .forms import SignUpForm
from .models import BaseUser
from utils.views_utils import LoginView

log = logging.getLogger('foster_home.{}'.format(__name__))


class LandingPageView(TemplateView):
    template_name = 'landing_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['signup_form'] = SignUpForm()
        return context


class SignInView(LoginView):
    template_name = 'signin.html'

    def get_success_url(self):
        self.success_url = reverse('users:user_profile',
                                   kwargs={'username': self.request.user.username})
        return super().get_success_url()


class SignUpView(FormView):
    form_class = SignUpForm
    template_name = 'signup.html'
    success_url = reverse_lazy('landing_page')

    def form_valid(self, form):
        user = form.register_user()
        ctx = {
            'protocol': self.request.scheme,
            'domain': self.request.get_host()
        }
        msg_body = 'Your activation key: {}'.format(user.generate_activation_uid())
        send_mail('REGISTRATION', msg_body, 'registration@foster_home.org', [user.email])
        return super().form_valid(form)


class UserActivationView(TemplateView):
    template_name = 'activation_failure.html'

    def get_user(self):
        user_model = get_user_model()
        user_pk = force_text(urlsafe_base64_decode(self.kwargs['uid64']))
        try:
            user = user_model.objects.get(pk=user_pk, is_active=False)
        except user_model.DoesNotExist:
            user = None
        return user

    def signature_valid(self, user):
        user.is_active = True
        user.save()
        return HttpResponseRedirect(reverse_lazy('users:signature_valid'))

    def signature_invalid(self):
        return self.render_to_response(self.get_context_data())

    def get(self, request, *args, **kwargs):
        # response = super().get(request, *args, **kwargs)
        user = self.get_user()
        signature = self.kwargs['signature']
        if user is not None and user.valid_signature(signature):
            return self.signature_valid(user)
        else:
            return self.signature_invalid()


class BaseUserDetailView(DetailView):
    model = BaseUser
    slug_url_kwarg = 'username'
    slug_field = 'username'


class BaseUserEditView(UpdateView):
    model = BaseUser
    fields = ('phone_no', 'address', 'call_before')
    slug_field = 'username'
    slug_url_kwarg = 'username'


landing_page_view = LandingPageView.as_view()
signin_view = SignInView.as_view()
signup_view = SignUpView.as_view()
user_activation_view = UserActivationView.as_view()
baseuser_detail_view = BaseUserDetailView.as_view()
baseuser_edit_view = BaseUserEditView.as_view()

foster_home/users/templates/includes/baseuser_edit_form.html
{% extends 'generic_form.html' %}

{% block form_action %}{% url "users:edit" username=object.username %}{% endblock form_action %}

{% block submit_text %}Edytuj profil{% endblock submit_text %}

foster_home/users/templates/includes/signup_form.html
{% load i18n widget_tweaks %}
{% if form.errors and not form.non_field_errors %}
    <p class="errornote">
        {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
{% endif %}

{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <p class="errornote">
            {{ error }}
        </p>
    {% endfor %}
{% endif %}


<form action="{% url "signup" %}" method="post" id="signup-form">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
            {{ field.errors }}
            <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
            {{ field|add_class:"form-control" }}
        </div>
    {% endfor %}
    <div class="form-row">
        <input class="btn btn-default" type="submit" value="{% trans 'Sign up' %}" />
    </div>
</form>

{% comment "Style proposal" %}
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
                <form role="form" method="post" action="{% url "signup" %}">
                    {% csrf_token %}
                    <h2>Zarejestruj się już dziś <small>Za darmo. Na zawsze.</small></h2>
                    <hr class="colorgraph">
                    <div class="form-group">
                        {% render_field signup_form.username class+="form-control input-lg" placeholder="Nazwa użytkownika" tabindex="3" %}
                    </div>
                    <div class="form-group">
                        {% render_field signup_form.email class+="form-control input-lg" placeholder="Adres email" tabindex="4" %}
                    </div>
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                {% render_field signup_form.password1 class+="form-control input-lg" placeholder="Hasło" tabindex="5" %}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="form-group">
                                {% render_field signup_form.password2 class+="form-control input-lg" placeholder="Powtórz hasło" tabindex="6" %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-4 col-sm-3 col-md-3">
					<span class="button-checkbox">
						<button type="button" class="btn" data-color="info" tabindex="7">Akceptuję</button>
                        {% render_field signup_form.terms_and_conds class+="hidden" %}
					</span>
                        </div>
                        <div class="col-xs-8 col-sm-9 col-md-9">
                            Klikając <strong class="label label-primary">zarejestruj</strong>akceptujesz <a href="#" data-toggle="modal" data-target="#t_and_c_m">regulamin</a> serwisu oraz politykę cookies.
                        </div>
                    </div>

                    <hr class="colorgraph">
                    <div class="row">
                        <div class="col-xs-12 col-md-12"><input type="submit" value="Zarejestruj" class="btn btn-primary btn-block btn-lg" tabindex="7"></div>
                    </div>
                </form>
            </div>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="t_and_c_m" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title" id="myModalLabel">Terms & Conditions</h4>
                    </div>
                    <div class="modal-body">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">I Agree</button>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
{% endcomment %}