foster_home/animals/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.animal_list_view, name='list'),
    url(r'^new-animal/$', views.animal_create_view, name='create'),
    url(r'^request-ownership/$', views.create_animal_ownership_request_view, name='create_ownership_request'),
    url(r'^request-ownership-(?P<pk>[0-9]+)/$', views.update_animal_ownership_request_status_view,
        name='update_ownership_request_status'),
    # url(r'^request-ownership/reject$', views.reject_animal_ownership_request_view,
    #     name='reject_ownership_request'),
    url(r'^animal-(?P<pk>[0-9]+)/$', views.animal_detail_view, name='detail'),
    url(r'^animal-(?P<pk>[0-9]+)/history/$', views.animalhistory_create_view, name='history'),
    url(r'^animal-(?P<pk>[0-9]+)/edit/$', views.animal_edit_view, name='edit'),
    url(r'animal-(?P<pk>[0-9]+)/confirm-change/$', views.set_ownership_confirmation_view,
        name='ownership_confirmation'),
]

foster_home/foster_home/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^$', 'users.views.landing_page_view', name='landing_page'),

    # TODO(kniski) find how to put login urlconf into users app
    url(r'^signin/$', 'users.views.signin_view', name='signin'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^signup/$', 'users.views.signup_view', name='signup'),
    url(r'^users/', include('users.urls', namespace='users')),  # TODO(kniski) design url for users list and user profile
    url(r'^animals/', include('animals.urls', namespace='animals')),

    # Examples:
    # url(r'^$', 'foster_home.views.home', name='home'),
    # url(r'^foster_home/', include('foster_home.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
]

# Uncomment the next line to serve media files in dev.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foster_home/users/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<username>[0-9A-Za-z_\-]+)/$', views.baseuser_detail_view, name='user_profile'),
    url(r'^(?P<username>[0-9A-Za-z_\-]+)/edit$', views.baseuser_edit_view, name='edit'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.user_activation_view, name='activation'),
]

foster_home/animals/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.core.validators import EMPTY_VALUES

from .models import Animal
from .models import AnimalSpecies
from .models import AnimalBreed
from .models import AnimalHistory
from gallery.models import Image


class AnimalCreateForm(forms.ModelForm):
    photo_1 = forms.ImageField(required=False)
    photo_2 = forms.ImageField(required=False)

    class Meta:
        model = Animal
        fields = ['name', 'species', 'breed', 'age', 'sex', 'owner']

    def save_images(self):
        img_kwargs = {
            'content_type': ContentType.objects.get_for_model(self.instance),
            'object_id': self.instance.pk
        }
        image_1 = Image(image=self.files['photo_1'], **img_kwargs)
        image_2 = Image(image=self.files['photo_2'], **img_kwargs)
        image_1.save()
        image_2.save()


class AnimalModelFilterForm(forms.Form):
    species = forms.ModelChoiceField(label=_('Species'),
                                     required=False,
                                     queryset=AnimalSpecies.objects.all(),
                                     to_field_name='name')
    breed = forms.ModelChoiceField(label=_('Breed'),
                                   required=False,
                                   queryset=AnimalBreed.objects.all(),
                                   to_field_name='name')
    sex = forms.ChoiceField(label=_('Sex'),
                            required=False,
                            choices=[(None, _('All'),),
                                     ('M', _('Male'),),
                                     ('F', _('Female'),)])
    sort_by = forms.ChoiceField(label=_('Sorting order'),
                                choices=[('age', _('Od najmłodszego'),),
                                         ('-age', _('Od najstarszego'),)])

    def get_ordering(self):
        if not hasattr(self, 'ordering'):
            self.ordering = self.cleaned_data.pop('sort_by', None)
        return self.ordering

    def save(self):
        cd = self.cleaned_data
        self.get_ordering()
        filter_kwargs = {}
        for label in self.fields.keys():
            try:
                value = cd[label]
                if value in EMPTY_VALUES:
                    continue
                filter_kwargs[label] = value
            except KeyError:
                continue
        return filter_kwargs


class AnimalHistoryForm(forms.ModelForm):
    class Meta:
        model = AnimalHistory
        fields = ['owner', 'animal']

foster_home/animals/views.py
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse_lazy
from django.forms.models import modelform_factory
from django.forms.widgets import HiddenInput
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.http import QueryDict
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import FormView
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.views.generic.edit import FormMixin
from django.views.generic.detail import SingleObjectMixin

from .forms import AnimalCreateForm
from .forms import AnimalHistoryForm
from .forms import AnimalModelFilterForm
from .models import Animal
from .models import AnimalHistory
from change_ownership.models import OwnershipRequest
from change_ownership.views import CreateOwnershipRequestView
from change_ownership.views import UpdateOwnershipRequestStatusView

ANIMAL_CONTENTYPE_ID = ContentType.objects.get(app_label="animals", model="animal").pk


class AnimalCreateView(CreateView):
    template_name_suffix = '_add'
    model = Animal
    form_class = AnimalCreateForm
    fields = ('name', 'species', 'breed', 'age', 'sex', 'owner')

    def get_form_class(self):
        widgets = {'owner': HiddenInput}
        return modelform_factory(self.model, form=AnimalCreateForm, fields=self.fields, widgets=widgets)

    def get_initial(self):
        initial = super().get_initial()
        initial['owner'] = self.request.user.pk
        return initial

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.FILES:
            form.save_images()
        return response


class AnimalDetailView(DetailView):
    model = Animal

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        context['already_requested'] = self.object.requested_by(user)
        context['is_owner'] = self.object.is_owner(user)
        context['is_future_owner'] = self.object.is_future_owner(user)
        return context


class AnimalEditView(UpdateView):
    model = Animal
    fields = ('name', 'age', 'species', 'breed')

    def form_valid(self, form):
        """
        Saves changes made to Animal and logs previous version on animal model.
        """
        old_object = self.get_object()
        self.object = form.save()
        current_object = self.object
        assert old_object.pk == current_object.pk
        diff = current_object.diff(old_object)
        AnimalHistory.objects.log_action(self.request.user.pk,
                                         current_object.pk,
                                         diff)
        return HttpResponseRedirect(self.get_success_url())


# TODO(kniski) add permission checking, only animal owner can add history entry
class AnimalHistoryCreateView(SingleObjectMixin, FormView):
    form_class = AnimalHistoryForm
    model = Animal
    template_name = 'animals/animalhistory_form.html'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, args, kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.request.method in ('POST', 'PUT'):
            data = {'description': self.request.POST['description'],
                    'animal': self.object.pk,
                    'owner': self.object.owner.pk}
            kwargs['data'] = data
        return kwargs

    def get_success_url(self):
        return reverse_lazy('animals:detail', kwargs=self.kwargs)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


# FIXME (kniski) it feels this view could be simpler
class AnimalListView(FormMixin, ListView):
    model = Animal
    form_class = AnimalModelFilterForm

    def get_queryset(self):
        queryset = self.model._default_manager.all()
        if self.queryset is not None:
            queryset = self.queryset
        ordering = self.get_ordering()
        if ordering:
            queryset = queryset.order_by(ordering)
        return queryset

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        response.context_data['form'] = self.get_form()
        return response

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            self.ordering = form.get_ordering()
            self.queryset = self.model._default_manager.filter(**form.save())
            return self.get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse_lazy('animals:list'))


class CreateAnimalOwnershipRequestView(CreateOwnershipRequestView):
    http_method_names = ['post']

    def notify_owner(self):
        owner = self.object.content_object.owner
        applicant = self.object.applicant
        subject = _('New adoption application')
        message = """
We are happy to inform you that someone wishes to adopt your animal.
You can verify profile of candidate by clicking link below.
{}""".format(self.request.build_absolute_uri(applicant.get_absolute_url()))
        owner.email_user(subject, message)

    def form_valid(self, form):
        self.object = form.save()
        self.notify_owner()
        return JsonResponse({'success': True})

    def form_invalid(self, form):
        return JsonResponse({'success': False, 'errors': form.errors})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        new_data = QueryDict('', mutable=True)
        new_data.update({'applicant': self.request.user.pk, 'content_type': ANIMAL_CONTENTYPE_ID})
        new_data.update(kwargs['data'])
        kwargs['data'] = new_data
        return kwargs


class UpdateAnimalOwnershipRequestStatusView(UpdateOwnershipRequestStatusView):
        http_method_names = ['post']
        success_url = reverse_lazy('animals:list')

        def send_reject_notification(self, user):
            subject = 'Ownership request rejected'
            message = """
We are sorry to inform you that your request to adopt {} has been rejected.
            """.format(self.object.content_object.name)
            user.email_user(subject, message)

        def send_accepted_notification(self):
            subject = 'Ownership request accepted'
            message = """
We are happy to inform you that your request to adopt {} has been accepted.
            """.format(self.object.content_object.name)
            self.object.applicant.email_user(subject, message)

        def form_valid(self, form):
            self.object = object = form.save()

            if object.status == object.REJECTED:
                self.send_reject_notification(object.applicant)
                object.delete()
            else:
                unaccepted_reqs = object.get_unaccepted()
                for unaccepted in unaccepted_reqs:
                    self.send_reject_notification(unaccepted.applicant)
                unaccepted_reqs.delete()
                self.send_accepted_notification()
            return JsonResponse({'success': True})

        def form_invalid(self, form):
            return JsonResponse({'success': False, 'errors': form.errors})


def SetOwnershipConfirmationView(request, pk):
    user = request.user
    animal = Animal.objects.get(pk=int(pk))
    ownership_req = animal.ownership_requests.get(status=OwnershipRequest.ACCEPTED)
    if animal.is_owner(user):
        ownership_req.set_owner_confirmation(user)
        ownership_req.status = OwnershipRequest.DONE
        ownership_req.save()
    elif animal.is_future_owner(user):
        ownership_req.set_applicant_confirmation(user)
        ownership_req.status = OwnershipRequest.DONE
        ownership_req.save()
    else:  # Neither owner or applicant
        return JsonResponse({'succes': False})

    if ownership_req.applicant_confirmation and ownership_req.owner_confirmation:
        animal.owner = ownership_req.applicant
        animal.save()

    return JsonResponse({'success': True})


animal_create_view = AnimalCreateView.as_view()
animal_detail_view = AnimalDetailView.as_view()
animal_list_view = AnimalListView.as_view()
animal_edit_view = AnimalEditView.as_view()
animalhistory_create_view = AnimalHistoryCreateView.as_view()
create_animal_ownership_request_view = CreateAnimalOwnershipRequestView.as_view()
update_animal_ownership_request_status_view = UpdateAnimalOwnershipRequestStatusView.as_view()
set_ownership_confirmation_view = SetOwnershipConfirmationView

foster_home/animals/templates/animals/animal_add.html
{% extends 'base.html' %}

{% block title %}Dodaj zwierzę{% endblock title %}
{% block page_title %}Dodaj zwierzę{% endblock page_title %}

{% block content %}
    {% include 'includes/animal_create_form.html' %}
{% endblock content %}

foster_home/animals/templates/animals/animal_detail.html
{% extends 'base.html' %}

{% block title %}{{ object.name }} - {{ object.species }} {{ object.breed }}{% endblock title %}

{% block page_title %} {{ object.name }}{% endblock page_title %}

{% block content %}
    <div class="row">
        {% for image in object.photos.all %}
            <div class="col-xs-6 col-md-3">
                <a href="#" class="thumbnail">
                    <img src="{{ image.image.url }}" alt="...">
                </a>
            </div>
        {% endfor %}
    </div>

    {% if object.during_transition %}
        <div class="alert alert-info" role="alert">
            {% if is_owner %}
                Twoje zwierzę jest w trakcie zmiany właściciela. Aby potwierdzić przekazania pupila kliknij w przycisk poniżej.
            {% elif is_future_owner %}
                To twój nowy pupil. Kliknij w przycisk poniżej kiedy twój nowy zwierzak będzie z bezpieczny z Tobą.
            {% endif %}
        <button id="ownershipreq-confirmation" type="button" class="btn btn-default" data-id="{{ object.pk }}" data-complete-text="Wysłano">Potwierdź</button>
        </div>
    {% endif %}

    <ul class="list-group">
        <li class="list-group-item">{{ object.name }}</li>
        <li class="list-group-item">{{ object.species }}</li>
        <li class="list-group-item">{{ object.breed }}</li>
        <li class="list-group-item">{{ object.age }}</li>
        <li class="list-group-item">{{ object.sex }}</li>
    </ul>
    <a href="{% url "animals:edit" pk=object.pk %}">Edytuj</a>

    {% if not object.during_transition %}
        <button id="request-ownership" class="btn btn-default {% if already_requested %} active{% endif %}" type="button" data-loading-text="Chwileczkę..." data-complete-text="Wysłano" data-animal="{{ object.pk }}" data-csrf="{{ csrf_token }}">Zaopiekuj się</button>
    {% endif %}

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">Historia zwierzęcia</div>
        <ul class="list-group">
            {% for entry in object.history.all %}
                <li class="list-group-item">{{ entry.entry_date }} - {{ entry.owner }} - {{ entry.diff }}</li>
            {% endfor %}
        </ul>
    </div>

    {% if not object.during_transition %}
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">Chętni do adopcji</div>
            <ul id="ownership-requests" class="list-group" data-csrf="{{ csrf_token }}">
                {% for ownership_req in object.ownership_requests.all %}
                    <li class="list-group-item" data-ownership="{{ ownership_req.pk }}">
                        <a href="{{ ownership_req.applicant.get_absolute_url }}">{{ ownership_req.applicant }}</a>
                        <button type="button" class="btn btn-default ownershipreq" data-status="ACC" data-complete-text="Wysłano">
                            <span class="glyphicon glyphicon-ok"></span>
                        </button>
                        <button type="button" class="btn btn-default ownershipreq" data-status="REJ" data-complete-text="Wysłano">
                            <span class="glyphicon glyphicon-remove"></span>
                        </button>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

{% endblock content %}

foster_home/animals/templates/animals/animal_form.html
{% extends 'base.html' %}

{% block title %}{{ object.name }} - {{ object.species }} {{ object.breed }} - edycja{% endblock title %}

{% block page_title %} {{ object.name }}{% endblock page_title %}

{% block content %}
    {% include 'includes/animal_edit_form.html' %}
{% endblock content %}

foster_home/animals/templates/animals/animal_list.html
{% extends 'base.html' %}

{% block title %}Zwierzęta{% endblock title %}

{% block content %}
    {% include 'includes/animal_list_filter_form.html' %}
    {% include 'includes/animal_list_table.html' %}
{% endblock content %}

foster_home/animals/templates/animals/animalhistory_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load i18n %}

{% block content %}

    {{ object }}

    {# FIXME(kniski) form error handling is duplicated in user app #}
    {% if form.errors and not form.non_field_errors %}
        <p class="errornote">
            {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
        </p>
    {% endif %}

    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <p class="errornote">
                {{ error }}
            </p>
        {% endfor %}
    {% endif %}
    <form action="{% url "animals:history" pk=object.pk %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.description.errors }}
            <label for="{{ form.description.id_for_label }}">{{ form.description.label }}:</label>
            {{ form.description|add_class:"form-control" }}
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
{% endblock content %}